DROP TABLE IF EXISTS champions;
CREATE TABLE champions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    quote TEXT NOT NULL,
    region TEXT NOT NULL
    role TEXT NOT NULL,
);